# Generated by Django 3.2.11 on 2022-01-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_commercial_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commercial',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commercial',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commercial',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commercial',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
