# Generated by Django 3.2.11 on 2022-01-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20220111_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercial',
            old_name='address',
            new_name='address_description',
        ),
        migrations.AddField(
            model_name='commercial',
            name='address_main_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
