# Generated by Django 3.2.11 on 2022-01-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20220111_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercial',
            old_name='address_description',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='address_main_text',
        ),
    ]
